---
title: "Testing"
output: html_document
date: "2023-08-03"
---

```{r}
enriched <- list()

species = "human"

if (species == "human"){
  Gene_GMTs <- c("HUMAN_KEGG", "HUMAN_MOUSE_Reactome", "HUMAN_WikiPathways", "HUMAN_GOBP",
                 "HUMAN_GOCC", "HUMAN_GOMF", "HUMAN_Hallmark", "HUMAN_MSigDB", "HUMAN_MOMENTABiocycEXP",
                 "HUMAN_MOMENTAMFNEXP")
  Phospho_GMTs <- c("HUMAN_PHOSPHO_UNIPROT")
  
  for (j in 1:length(enrich_geneList)){
    contrast_enriched <- list()
    phospho_enriched <- list()
    for (i in 1:length(enrich_geneList[[j]])){
      if (grepl("_GSEA", names(enrich_geneList)[j])){
        for(k in 1:length(Gene_GMTs)){
          message(names(enrich_geneList)[j], Gene_GMTs[k])
          enrich <- clusterProfilerEnrichment(geneList = enrich_geneList[[j]][[i]],
                                              gmt = Gene_GMTs[k],
                                              enrichment = "ranked",
                                              pval_cutoff = 0.05)
          # if (dim(enrich)[1] != 0){
            contrast_enriched[[paste0(Gene_GMTs[k])]] <- enrich
          # }
        }
        enriched[[paste0(sub("_.*", "", names(enrich_geneList)[j]), "_", names(enrich_geneList[[j]])[i])]] <- contrast_enriched
      } else if (grepl("_PKSEA", names(enrich_geneList)[j])){
        message(names(enrich_geneList)[j])
        enrich <- clusterProfilerEnrichment(geneList = enrich_geneList[[j]][[i]],
                                            gmt = "HUMAN_PHOSPHO_UNIPROT",
                                            enrichment = "ranked",
                                            pval_cutoff = 0.05)
        # if (dim(enrich)[1] != 0){
          enriched[[paste0(sub("_.*", "", names(enrich_geneList)[j]), "_", names(enrich_geneList[[j]])[i])]][paste0("HUMAN_PHOSPHO_UNIPROT")] <- enrich
        # }
      }
    }
  }
}
```


```{r}
# setwd("~/Downloads/ShinyApp_DEV")

library(Biobase)
annot_initial <- data.frame(openxlsx::read.xlsx("~/Documents/ShinyApp_DEV/example_data/example_annotation.xlsx",
                                        2,
                                        colNames = TRUE))

annot_files <- data.frame(openxlsx::read.xlsx("~/Documents/ShinyApp_DEV/example_data/example_annotation.xlsx",
                                        1,
                                        colNames = FALSE))

source("formatAnnotation.R")
annot <- formatAnnotation(annot_initial, group = "Treatment")

data_input <- read.table("~/Documents/ShinyApp_DEV/example_data/example_proteingroups.txt", 
                         header = TRUE, 
                         sep = "\t")

source("makeEset.R")
eset <- makeEset(data = data_input, 
                 annotate = annot, 
                 type = "Proteomics", 
                 log_transform = TRUE,
                 data_format = "ProteinGroups", 
                 uniprot_annotation = FALSE)

source("performNormalization.R")
eset <- intensityNorm(eset = eset, 
                      norm = "quantile", 
                      type = "Proteomics", 
                      zero_cutoff = 0.3, 
                      min_feature = 0.01,
                      norm_by_batches = F)

contrastgroups = c("Glucose", "NoGlucose")
contrast_strings = c()
contrast_strings <- sapply(combn(rev(contrastgroups), 2, simplify = F), FUN = function(l)paste(l, collapse = "-"))
contrast_strings <- c(contrast_strings, sapply(combn(contrastgroups, 2, simplify = F), FUN = function(l)paste(l, collapse = "-")))

eset <- eset[,which(pData(eset)$Group %in% contrastgroups)]
factor <- factor(pData(eset)$Group)

design <- stats::model.matrix(~ 0 + factor);

library(Biobase)
data <- limma::removeBatchEffect(eset, eset$Pairs, design=design)
data_corrected <- ExpressionSet(assayData = data)
pData(data_corrected) <- pData(eset);
rownames(pData(data_corrected)) <- colnames(data);
fData(data_corrected) <- fData(eset);
PCA <- drawPCA(eset = data_corrected, 
        x_axis = "PC1", 
        y_axis = "PC2", 
        type = "Proteomics", 
        color = "Set1",
        include_densities = FALSE,
        shapes = FALSE,
        title_add = "",
        add_labels = FALSE,
        add_ellipse = FALSE)

PCA

colnames(design) <- make.names(colnames(design));
colnames(design) <- gsub("factor", "", colnames(design))

fit <- limma::lmFit(eset, design);

contrast_matrix <- limma::makeContrasts(contrasts = contrast_strings, levels = design);

fit <- limma::contrasts.fit(fit, contrast_matrix);
fit <- limma::eBayes(fit);
```

```{r}
outlier_cols <- c("Proteomics_Glucose2")
type <- "Proteomics"

print(exprs(eset))

for (i in outlier_cols){
  print(i)
  
  if(grepl(type, i)){
    column <- gsub(".*_", "", i)
    print(column)
    column <- which(colnames(exprs(eset)) == column)
    eset_2 <- eset[, -c(column)]
  }
}

print(exprs(eset_2))

pData(eset)
```


```{r}
dataframe <- as.data.frame(Biobase::exprs(eset))

contrastgroups = unique(annot$Group)
logfc_index <- c();
  
  # CALCULATE MEAN VALUE PER GROUP
  for(j in 1:length(contrastgroups)){
    if(sum(pData(eset)$Group == contrastgroups[j]) > 1){
      dataframe[, paste("mean_", contrastgroups[j], sep = "")] <- 
        rowMeans(exprs(eset)[, pData(eset)$Group == contrastgroups[j]])
      dataframe[, paste("sd_", contrastgroups[j], sep = "")] <- 
        apply((exprs(eset)[, pData(eset)$Group == contrastgroups[j]]), 1, sd, na.rm = TRUE)
      dataframe[, paste("upperlimit_", contrastgroups[j], sep = "")] <- 
        dataframe[, paste("mean_", contrastgroups[j], sep = "")] + dataframe[, paste("sd_", contrastgroups[j], sep = "")]
      dataframe[, paste("lowerlimit_", contrastgroups[j], sep = "")] <- 
        dataframe[, paste("mean_", contrastgroups[j], sep = "")] - dataframe[, paste("sd_", contrastgroups[j], sep = "")]
      
      start_col <- grep(contrastgroups[j], colnames(dataframe))[1]
      for (i in start_col:(start_col - 1 + sum(pData(eset)$Group == contrastgroups[j]))){
        dataframe[,i][(dataframe[,i] > dataframe[, paste("upperlimit_", contrastgroups[j], sep = "")]) |
                          (dataframe[,i] < dataframe[, paste("lowerlimit_", contrastgroups[j], sep = "")])] <- NA
      }
      
    } else {
      dataframe[, paste("mean_", contrastgroups[j], sep = "")] <- exprs(eset)[, pData(eset)$Group == contrastgroups[j]] 
      dataframe[, paste("sd_", contrastgroups[j], sep = "")] <- exprs(eset)[, pData(eset)$Group == contrastgroups[j]] 
    }
  }
  
  # CREATE LOG FOLD CHANGE B/W EACH PAIRING OF GROUPS
  for(j in 1:(length(contrastgroups) - 1)){
    for(k in 2:(length(contrastgroups))){
      col_name <- paste("logfc_", contrastgroups[k], "_", contrastgroups[j], sep = "");
      dataframe[col_name] <- (fData(eset)[, paste("mean_", contrastgroups[k], sep = "")] -
                                    fData(eset)[, paste("mean_", contrastgroups[j], sep = "")]) 
      col_name_rev <- paste("logfc_", contrastgroups[j], "_", contrastgroups[k], sep = "")
      dataframe[col_name_rev] <- (fData(eset)[, paste("mean_", contrastgroups[j], sep = "")] -
                                    fData(eset)[, paste("mean_", contrastgroups[k], sep = "")]) 
      
      logfc_index <- c(logfc_index, col_name, col_name_rev)
    }
  }
  
  # We calculate a maximum fold change value across all groups as a way to see which features are changing most across all groups.
  # This is analogous to the F-statistic from the differential analysis.
  fData(eset)[, "logfc_Overall"] <- apply(fData(eset)[, grep("mean", colnames(fData(eset)))], 1, function(x) max(x) - min(x))
  
  logfc_index <- unique(logfc_index);
  
fData(eset)
```



```{r}
setwd("~/Downloads/ShinyApp_DEV")

library(Biobase)
annot <- data.frame(openxlsx::read.xlsx("~/Downloads/ShinyApp_DEV/example_data/example_annotation.xlsx",
                                        2,
                                        colNames = TRUE))

annot_files <- data.frame(openxlsx::read.xlsx("~/Downloads/ShinyApp_DEV/example_data/example_annotation.xlsx",
                                        1,
                                        colNames = FALSE))

source("formatAnnotation.R")
annot <- formatAnnotation(annot, group = "Treatment")

data_input <- read.table("~/Downloads/ShinyApp_DEV/example_data/example_proteingroups.txt", 
                         header = TRUE, 
                         sep = "\t")

source("makeEset.R")
eset <- makeEset(data = data_input, 
                 annotate = annot, 
                 type = "Proteomics", 
                 log_transform = TRUE,
                 data_format = "ProteinGroups", 
                 uniprot_annotation = FALSE)

source("performNormalization.R")
eset <- intensityNorm(eset = eset, 
                      norm = "quantile", 
                      type = "Proteomics", 
                      zero_cutoff = 0.3, 
                      min_feature = 0.01,
                      norm_by_batches = F)

contrastgroups = c("Glucose", "NoGlucose")
contrast_strings = c()
contrast_strings <- sapply(combn(rev(contrastgroups), 2, simplify = F), FUN = function(l)paste(l, collapse = "-"))
contrast_strings <- c(contrast_strings, sapply(combn(contrastgroups, 2, simplify = F), FUN = function(l)paste(l, collapse = "-")))

eset <- eset[,which(pData(eset)$Group %in% contrastgroups)]
factor <- factor(pData(eset)$Group)

design <- stats::model.matrix(~ 0 + factor);

colnames(design) <- make.names(colnames(design));
colnames(design) <- gsub("factor", "", colnames(design))

fit <- limma::lmFit(eset, design);

contrast_matrix <- limma::makeContrasts(contrasts = contrast_strings, levels = design);

fit <- limma::contrasts.fit(fit, contrast_matrix);
fit <- limma::eBayes(fit);

top_sum <- limma::topTable(fit, adjust.method="BH", n=Inf, sort.by= 'p', coef=1);
ranked <- cbind(top_sum[,'Gene'], top_sum[,'logFC'])

colnames(ranked)<-c("GeneName", "rank")
ranked <- ranked[ranked[,"GeneName"]!="",]
ranked <- ranked[order(abs(as.numeric(ranked[,"rank"])), decreasing=TRUE),]
ranked <- ranked[!duplicated(ranked[,"GeneName"]),]
ranked <- ranked[order(as.numeric(ranked[,"rank"]), decreasing=TRUE),]

top_sum$fcSign = sign(top_sum$logFC)
top_sum$logP = -log10(top_sum$P.Value)
top_sum$metric = top_sum$logP / top_sum$fcSign
ranked <- top_sum[,c("Gene", "metric")]

# fgsea <- read.delim("C:/Users/pottegra/Documents/fgsea_Proteomics_Glucose_NoGlucose_Human_GOBP_AllPathways_no_GO_iea_November_07_2023_symbol.gmt.txt", header = TRUE, sep = "\t")
```

```{r}
## PHOSPHOPROTEOMICS ###########################################################

raw_annot_phospho <- data.frame(openxlsx::read.xlsx("~/Downloads/ShinyApp_V19/example_data/example_annotation.xlsx",
                                        2,
                                        colNames = TRUE))

files_annot_phospho <- data.frame(openxlsx::read.xlsx("~/Downloads/ShinyApp_V19/example_data/example_annotation.xlsx",
                                        1,
                                        colNames = FALSE))

source("formatAnnotation.R")
annot_phospho <- formatAnnotation(raw_annot_phospho, group = "Treatment")

data_input_phospho <- read.table("~/Downloads/ShinyApp_V19/example_data/example_phosphosites.txt", 
                         header = TRUE, 
                         sep = "\t")

source("makeEset.R")
prenorm_eset_phospho <- makeEset(data = data_input_phospho, 
                             annotate = annot_phospho, 
                             type = "Phosphoproteomics", 
                             log_transform = TRUE,
                             data_format = "PhosphoSites", 
                             uniprot_annotation = TRUE)

source("performNormalization.R")
eset_phospho <- intensityNorm(eset = prenorm_eset_phospho, 
                              norm = "quantile", 
                              type = "Phosphoproteomics", 
                              zero_cutoff = 0.3, 
                              min_feature = 0.01,
                              norm_by_batches = F)

contrastgroups = c("Glucose", "NoGlucose")
contrast_strings = c()
contrast_strings <- sapply(combn(rev(contrastgroups), 2, simplify = F), FUN = function(l)paste(l, collapse = "-"))
contrast_strings <- c(contrast_strings, sapply(combn(contrastgroups, 2, simplify = F), FUN = function(l)paste(l, collapse = "-")))

eset_phospho <- eset[,which(pData(eset)$Group %in% contrastgroups)]
factor <- factor(pData(eset_phospho)$Group)

design <- stats::model.matrix(~ 0 + factor);

colnames(design) <- make.names(colnames(design));
colnames(design) <- gsub("factor", "", colnames(design))

fit_phospho <- limma::lmFit(eset_phospho, design);

contrast_matrix <- limma::makeContrasts(contrasts = contrast_strings, levels = design);

fit_phospho <- limma::contrasts.fit(fit_phospho, contrast_matrix);
fit_phospho <- limma::eBayes(fit_phospho);

top_sum_phospho <- limma::topTable(fit_phospho, adjust.method = "BH", n = Inf, sort.by = 'p', coef = 1);
ranked_phospho <- cbind(top_sum[,'Gene'], top_sum[,'logFC'])

colnames(ranked_phospho)<-c("GeneName", "rank")
ranked_phospho <- ranked_phospho[ranked_phospho[,"GeneName"] != "",]
ranked_phospho <- ranked_phospho[order(abs(as.numeric(ranked_phospho[,"rank"])), decreasing = TRUE),]
ranked_phospho <- ranked_phospho[!duplicated(ranked_phospho[,"GeneName"]),]
ranked_phospho <- ranked_phospho[order(as.numeric(ranked_phospho[,"rank"]), decreasing = TRUE),]

top_sum_phospho$fcSign = sign(top_sum_phospho$logFC)
top_sum_phospho$logP = -log10(top_sum_phospho$P.Value)
top_sum_phospho$metric = top_sum_phospho$logP / top_sum_phospho$fcSign
ranked_phospho <- top_sum_phospho[,c("Gene", "metric")]

# fgsea <- read.delim("C:/Users/pottegra/Documents/fgsea_Proteomics_Glucose_NoGlucose_Human_GOBP_AllPathways_no_GO_iea_November_07_2023_symbol.gmt.txt", header = TRUE, sep = "\t")
```
```{r}
setwd("~/ShinyApp_V17")

library(Biobase)
annot <- data.frame(openxlsx::read.xlsx("/Users/pottegra/OneDrive - Oregon Health & Science University/Documents/Data_Processing/Omics_EXAMPLE_NEW/Annotation_Glucose.xlsx",
                                        2,
                                        colNames = TRUE))

source("formatAnnotation.R")
annot <- formatAnnotation(annot, group = "Treatment")

data_input <- read.table("/Users/pottegra/OneDrive - Oregon Health & Science University/Documents/Data_Processing/Omics_EXAMPLE_NEW/example_PhosphoSites.txt", 
                         header = TRUE, 
                         sep = "\t")

source("makeEset.R")
eset <- makeEset(data = data_input, 
                 annotate = annot, 
                 type = "Phosphoproteomics", 
                 log_transform=TRUE,
                 data_format = "Sites..MQ.", 
                 uniprot_annotation=FALSE)


source("intensityNorm.R")
eset <- intensityNorm(eset = eset, 
                      norm = "quantile", 
                      type = "Phosphoproteomics", 
                      zero_cutoff=0.3, 
                      min_feature=0.01,
                      norm_by_batches=F)

contrastgroups = c("Glucose", "NoGlucose")
contrast_strings = c()
contrast_strings <- sapply(combn(rev(contrastgroups), 2, simplify = F), FUN = function(l)paste(l, collapse = "-"))
contrast_strings <- c(contrast_strings, sapply(combn(contrastgroups, 2, simplify = F), FUN = function(l)paste(l, collapse = "-")))

eset <- eset[,which(pData(eset)$Group %in% contrastgroups)]
factor <- factor(pData(eset)$Group)

design <- stats::model.matrix(~ 0 + factor);

colnames(design) <- make.names(colnames(design));
colnames(design) <- gsub("factor", "", colnames(design))

fit <- limma::lmFit(eset, design);

contrast_matrix <- limma::makeContrasts(contrasts = contrast_strings, levels = design);

fit <- limma::contrasts.fit(fit, contrast_matrix);
fit <- limma::eBayes(fit);

top_sum <- limma::topTable(fit, adjust.method="BH", n=Inf, sort.by= 'p', coef=1);

# phosphoID <- paste0(top_sum[,"Protein"], ";", top_sum[,"Amino.acid"],  top_sum[,"Position"])
# ranked <- cbind(phosphoID, top_sum[,'logFC'])
    
# colnames(ranked)<-c("GeneName", "rank")
# ranked <- ranked[ranked[,"GeneName"]!="",]
# ranked <- ranked[order(abs(as.numeric(ranked[,"rank"])), decreasing=TRUE),]
# ranked <- ranked[!duplicated(ranked[,"GeneName"]),]
# ranked <- ranked[order(as.numeric(ranked[,"rank"]), decreasing=TRUE),]

top_sum$fcSign = sign(top_sum$logFC)
top_sum$logP = -log10(top_sum$P.Value)
top_sum$metric = top_sum$logP / top_sum$fcSign
ranked <- cbind(paste0(top_sum[,"Protein"], ";", top_sum[,"Amino.acid"], top_sum[,"Position"]), top_sum[,"metric"])
    
    
```

```{r}
annot <- data.frame(openxlsx::read.xlsx("/Users/pottegra/OneDrive - Oregon Health & Science University/Documents/Data_Processing/Omics_EXAMPLE_NEW/Annotation_GlucoseExample.xlsx", 1, colNames = FALSE))
annot <- annot[-(1:10),]
annot <- annot[,-c(2,4)]
colnames(annot) <- c("File", "Format")
annot <- na.omit(annot)

file <- "example_proteinGroups.xlsx"
row <- annot[grep(file, annot$File), ]
data_format <- row$Format
```


```{r}
enriched_GSEA_table = enriched_GSEA@result %>%
      as.data.frame() %>%
      tibble::remove_rownames()

enriched_ORA_table = enriched_ORA@result %>%
      as.data.frame() %>%
      tibble::remove_rownames() %>%
      dplyr::select(Description, p.adjust, Count, GeneRatio, intersection = geneID) %>%
      dplyr::mutate(intersection = stringr::str_replace_all(intersection, "/", ", "))
```

```{r}
library(Biobase)
annot <- data.frame(openxlsx::read.xlsx("/Users/pottegra/Documents/Data_Processing/2023_08_14_Omics_Nazmin/NEW_Annotation_PDdata_20230814.xlsx",
                                        2,
                                        colNames = TRUE))

source("formatAnnotation.R")
annot <- formatAnnotation(annot, group = "Treatment")

data_input <- read.delim("/Users/pottegra/Documents/Data_Processing/2023_08_14_Omics_Nazmin/ORIGINAL_2022-08-08_PISA_STAN_PD.txt", 
                         header = TRUE, 
                         sep = "\t")

source("makeEset.R")
eset <- makeEset(data = data_input, 
                 annotate = annot, 
                 type = "Proteomics", 
                 log_transform=TRUE,
                 data_format = "Protein.Groups..MQ.", 
                 uniprot_annotation=FALSE)

source("intensityNorm.R")
eset <- intensityNorm(eset = eset, 
                      norm = "quantile", 
                      type = "Proteomics", 
                      zero_cutoff=0.3, 
                      min_feature=0.01,
                      norm_by_batches=F)

```

```{r}
library(Biobase)
annot <- data.frame(openxlsx::read.xlsx("/Users/pottegra/Documents/Data_Processing/2023_09_11_Omics_Indranil/Annotation_MouseBrain.xlsx",
                                        2,
                                        colNames = TRUE))

annot_pageone <- data.frame(openxlsx::read.xlsx("/Users/pottegra/Documents/Data_Processing/2023_09_11_Omics_Indranil/Annotation_MouseBrain.xlsx", 1, colNames = FALSE))

source("formatAnnotation.R")
annot <- formatAnnotation(annot,
                          group = "Treatment")


group = "Treatment"
  
annot_new$Group <- annot_new[,group]
contrasts <- unique(gsub("\\.","", make.names(na.omit(annot_new$Group))))

if(length(annot$Group) == length(contrasts)){ ## hack // Group is sometimes used differently in other pipelines
annot$Group = contrasts

} else {
    annot[,"Group"] <- gsub("\\.", "", make.names(annot[,"Group"]))
    
}

annot[,"SampleName"] <- gsub("\\.", "", make.names(make.unique(as.character(annot[,"SampleName"]))))

return(annot)

```

```{r}
emat_sel <- exprs(eset)
exprs_eset <- emat_sel
vars <- sort(apply(exprs_eset, 1, var), decreasing = TRUE)[1:100]
emat_sel <- exprs_eset[names(vars),]
emat_sel <- stats::na.omit(t(scale(t(emat_sel))))
emat_sel[emat_sel < -2] <- -2
emat_sel[emat_sel > 2] <- 2

heatmaply(emat_sel, colors = colorRampPalette(brewer.pal(11, "Spectral")), seriate = "mean", col_side_colors = pData(eset)$Group,  showticklabels = c(TRUE, FALSE))
```

```{r}
metaboanalyst_input <- utils::read.delim("/Users/pottegra/Downloads/metaboanalyst_input.csv", header = TRUE, sep = ",")
metaboanalyst_input <- metaboanalyst_input[-1,]
colnames(metaboanalyst_input)[1] <- "Label"
metaboanalyst_input[,"mz"] = sub('_.*', '', metaboanalyst_input[,"Label"])
metaboanalyst_input[,"rt"] = sub('.*_', '', metaboanalyst_input[,"Label"])
```

```{r}
gmt_expanded <- read.delim("/Users/pottegra/Downloads/gene_expanded_human_hsa_biocyc.gmt", header = FALSE)
gmt_targetsize <- read.delim("/Users/pottegra/Downloads/gene_targetSize_human_hsa_biocyc.gmt", header = FALSE)
gmt_human <- read.delim("/Users/pottegra/Downloads/Human_GOBP_AllPathways_no_GO_iea_October_01_2023_symbol.gmt", header = FALSE)
gmt_fly <- read.delim("/Users/pottegra/Downloads/Drosophila_melanogaster_GSEA_GO_sets_all_symbols_April_2015.gmt", header = FALSE)


overlap <- merge(gmt_expanded, gmt_targetsize, by = 'V1')
```

```{r}
gmt <- read.delim("/Users/pottegra/Downloads/Human_GO_AllPathways_no_GO_iea_November_07_2023_symbol.gmt.txt", header = FALSE)
```

```{r}

library("ggpubr")
set.seed(1234)
data <- dplyr::sample_n(data.frame(exprs(eset_norm)), 5000)
shapiro.test(data[, 1])
ggqqplot(data[, 2])
ggdensity(data[, 2], fill = "lightgray")

ks.test(exprs(eset)[,1], "pnorm")
```

```{r}

library(Biobase)
annot <- data.frame(openxlsx::read.xlsx("/Users/pottegra/OneDrive - Oregon Health & Science University/Documents/Data_Processing/Omics_EXAMPLE_NEW/Annotation_GlucoseExample.xlsx",
                                        2,
                                        colNames = TRUE))

annot_files <- data.frame(openxlsx::read.xlsx("/Users/pottegra/OneDrive - Oregon Health & Science University/Documents/Data_Processing/Omics_EXAMPLE_NEW/Annotation_GlucoseExample.xlsx",
                                        1,
                                        colNames = FALSE))


annot <- formatAnnotation(annot, group = "Treatment")

data <- list()

data[[1]] <- read.table("/Users/pottegra/OneDrive - Oregon Health & Science University/Documents/Data_Processing/Omics_EXAMPLE_NEW/example_proteinGroups.txt", 
                         header = TRUE, 
                         sep = "\t")
data[[2]] <- read.table("/Users/pottegra/OneDrive - Oregon Health & Science University/Documents/Data_Processing/Omics_EXAMPLE_NEW/example_PhosphoSites.txt", 
                         header = TRUE, 
                         sep = "\t")
data[[3]] <- read.table("/Users/pottegra/OneDrive - Oregon Health & Science University/Documents/Data_Processing/Omics_EXAMPLE_NEW/example_MetPos.txt", 
                         header = TRUE, 
                         sep = "\t")
data[[4]] <- read.table("/Users/pottegra/OneDrive - Oregon Health & Science University/Documents/Data_Processing/Omics_EXAMPLE_NEW/example_MetNeg.txt", 
                         header = TRUE, 
                         sep = "\t")

eset <- list()
type = c("Proteomics", "Phosphoproteomics", "Metabolites_Neg", "Metabolites_Pos")
data_format = c("ProteinGroups", "PhosphoSites", "MetaboliteNeg", "MetabolitePos")
for (i in 1:4){
  eset[[i]] <- makeEset(data = data[[i]], 
                   annotate = annot, 
                   type = type[i], 
                   log_transform = TRUE,
                   data_format = data_format[i], 
                   uniprot_annotation = FALSE)
}

# withProgress(message = "Starting data cleaning...", value = 0, {
for (i in 1:4){
  # incProgress(amount = (1/(length(input$data_file[, 1]))), detail = paste("Filtering, normalizing, and imputing dataset", i))
  
  eset[[i]] <- intensityNorm(eset = eset[[i]],
                             norm = input$norm_eset,
                             type = type()[i],
                             zero_cutoff = input$zero_cutoff,
                             impute_missing = input$impute_missing)
}

linear_models <- list()
for (i in 1:length(type)){
  linear_models[[i]] <- limmaLM(annot = annotation(),
                                eset = eset[[i]],
                                samples = c("Glucose", "NoGlucose"),
                                time_series = FALSE,
                                contrast_fit = TRUE,
                                contrasts_subset = "Glucose-NoGlucose",
                                covariate = FALSE)
}

geneList <- list()
report_coef_options <- c("Glucose-NoGlucose", "Glucose-NoGlucose")
for (j in 1:4){
  sub_geneList <- list()
  # report_coef_options = "NoGlucose-Glucose"
  if (data_format[j] == "ProteinGroups" | data_format[j] == "PhosphoSites"){
      for (i in 1:length(report_coef_options)){
        genes <- calculateGeneList(fit = linear_models[[j]],
                                   coef = report_coef_options[i],
                                   enrichment_type = "GSEA")
        sub_geneList[[i]] <- genes 
      }
    geneList[[j]] <- sub_geneList
  }
}

enriched <- geneList

setwd("~/ShinyApp_V18")
for (i in 1:length(geneList)){
  for (j in 1:length(geneList[[i]])){
    enrich <- clusterProfilerEnrichment(geneList = geneList[[1]][[1]],
                                        gmt = "HUMAN_KEGG",
                                        enrichment = "unranked",
                                        pval_cutoff = 1)
    enriched[[i]][[j]] <- enrich
  }
}
```

